//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Banner
    {
        public int Banner_ID { get; set; }
        [DisplayName("Hình Ảnh")]
        [Required(ErrorMessage = "Hình ảnh không được để trống.")]
        [StringLength(250, ErrorMessage = "Đường dẫn hình ảnh không được vượt quá 250 ký tự.")]
        public string HinhAnh { get; set; }

        [DisplayName("Mô Tả")]
        [StringLength(500, ErrorMessage = "Mô tả không được vượt quá 500 ký tự.")]
        public string MoTa { get; set; }

        [DisplayName("Liên Kết")]
        [StringLength(250, ErrorMessage = "Đường dẫn liên kết không được vượt quá 250 ký tự.")]
        public string Link { get; set; }

        [DisplayName("Thứ Tự")]
        [Required(ErrorMessage = "Thứ tự không được để trống.")]
        [Range(0, int.MaxValue, ErrorMessage = "Thứ tự không được là số âm.")]
        public Nullable<int> ThuTu { get; set; }
    }
}
