//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_TheLoai
    {
        public int ID { get; set; }
        public int DanhMuc_ID { get; set; }
        public int TheLoai_ID { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
