//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int IDdgsp { get; set; }
        public int IDkh { get; set; }
        public int IDsp { get; set; }
        public Nullable<int> IDDonHang { get; set; }
        public int DiemDanhGia { get; set; }
        public string NhanXet { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public string PhanHoi { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
