//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DanhGiaSanPham = new HashSet<DanhGiaSanPham>();
            this.DonHangCT = new HashSet<DonHangCT>();
            this.FlashSale_SanPham = new HashSet<FlashSale_SanPham>();
        }
    
        public int IDsp { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public int IDtl { get; set; }
        public decimal GiaBan { get; set; }
        public string HinhAnh { get; set; }
        public int IDtg { get; set; }
        public int IDnxb { get; set; }
        public int IDkm { get; set; }
        public int SoLuong { get; set; }
        public string TrangThaiSach { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> DiemDanhGiaTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangCT> DonHangCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlashSale_SanPham> FlashSale_SanPham { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
