//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Slide
    {
        public int SlideID { get; set; }
        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "Hình ảnh không được để trống")]
        public string HinhAnh { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Mô tả không được để trống")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Link không được để trống")]
        public string Link { get; set; }

        [DisplayName("Thứ tự")]
        [Required(ErrorMessage = "Thứ tự không được để trống")]
        public Nullable<int> ThuTu { get; set; }
    }
}
